
version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nodesequelize
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: example
      DB_NAME: nodesequelize
      SESSION_SECRET: really_secret
    depends_on:
      - db
volumes:
  dbdata:
